src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use DateTime;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\DBAL\Types\Types;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;


#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: 'user')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private $id;

    #[ORM\Column(length:180,unique:true)]
    private string $username;

    #[ORM\Column(type:Types::JSON)]
    private $roles = [];

    #[ORM\Column]
    private string $password;

    #[ORM\Column(length:255)]
    private string $email;

    #[ORM\Column]
    private bool $is_active;

    #[ORM\Column(length:255,unique:true)]
    private ?string $rp_token;

    #[ORM\Column]
    private ?DateTime $rp_token_created_at;

    #[ORM\Column(length:255,unique:true)]
    private ?string $confirmation_token;

    #[ORM\Column(length:255)]
    private ?string $wordpressID;

    #[ORM\Column(length:255)]
    private $wordpressUsername;

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getUserIdentifier(): string
    {
        return $this->getUsername();
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRole(string $role): self
    {
        $roles = $this->roles;
        $roles[] = $role;
        $this->roles = array_unique($roles);
        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getIsActive(): ?bool
    {
        return $this->is_active;
    }

    public function setIsActive(bool $is_active): self
    {
        $this->is_active = $is_active;

        return $this;
    }

    public function getRpToken(): ?string
    {
        return $this->rp_token;
    }

    public function setRpToken(?string $rp_token): self
    {
        $this->rp_token = $rp_token;

        return $this;
    }

    public function getRpTokenCreatedAt(): ?\DateTimeInterface
    {
        return $this->rp_token_created_at;
    }

    public function getRpDelay(): ?\DateTime
    {
        return date_add($this->rp_token_created_at,date_interval_create_from_date_string('1 day'));
    }

    public function setRpTokenCreatedAt(?\DateTimeInterface $rp_token_created_at): self
    {
        $this->rp_token_created_at = $rp_token_created_at;

        return $this;
    }

    public function generateRpToken(){
        $token = md5(uniqid());
        $this->setRpToken($token);
        $this->setRpTokenCreatedAt(new \DateTime('now'));
    }

    public function getConfirmationToken(): ?string
    {
        return $this->confirmation_token;
    }

    public function setConfirmationToken(?string $confirmation_token): self
    {
        $this->confirmation_token = $confirmation_token;

        return $this;
    }

    public function getWordpressID(): ?string
    {
        return $this->wordpressID;
    }

    public function setWordpressID(?string $wordpressID): self
    {
        $this->wordpressID = $wordpressID;

        return $this;
    }

    public function getWordpressUsername(): ?string
    {
        return $this->wordpressUsername;
    }

    public function setWordpressUsername(?string $wordpressUsername): self
    {
        $this->wordpressUsername = $wordpressUsername;

        return $this;
    }

    static function randomPassword() {
        $alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890-{}#[]=+*!&$%?,;:';
        $pass = array(); //remember to declare $pass as an array
        $alphaLength = strlen($alphabet) - 1; //put the length -1 in cache
        for ($i = 0; $i < 10; $i++) {
            $n = rand(0, $alphaLength);
            $pass[] = $alphabet[$n];
        }
        return implode($pass); //turn the array into a string
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\UserRepository;
use App\Service\ConfigService;
use App\Service\MailService;
use phpDocumentor\Reflection\Types\Integer;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Exception\InvalidCsrfTokenException;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Csrf\CsrfToken;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    private $userRepository;
    private $csrfTokenManager;
    private $config;
    private $urlGenerator;
    private $mailer;

    public function __construct(
        UserRepository $userRepository,
        CsrfTokenManagerInterface $csrfTokenManager,
        ConfigService $configService,
        MailService $mailerService,
        UrlGeneratorInterface $urlGenerator
    )
    {
        $this->userRepository = $userRepository;
        $this->csrfTokenManager = $csrfTokenManager;
        $this->config = $configService;
        $this->mailer = $mailerService;
        $this->urlGenerator = $urlGenerator;
    }

    #[Route('/logout', name: 'app_logout')]
    public function logout()
    {
        throw new \Exception('Will be intercepted before getting here');
    }

    #[Route('/login', name: 'app_login')]
    public function login(Request $request,AuthenticationUtils $authenticationUtils)
    {
        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        if ($error){
            $session = $request->getSession();
            $session->getFlashBag()->add('error', $error->getMessageKey());
        }
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig',array('last_username' => $lastUsername));
    }

    #[Route('/oauth_login', name: 'app_oauth')]
    public function oauth_login(){

        $url = $this->config->getValue('app/oauth_url')."oauth/authorize";

        $redirect_url = $this->urlGenerator->generate('app_login',array('wordpress-oauth-provider'=>true),UrlGeneratorInterface::ABSOLUTE_URL);

        $query_string = http_build_query([
            'client_id' => $this->config->getValue('app/oauth_client_id'),
            'redirect_uri' => $redirect_url,
            'response_type' => "code",
            'scope' => "basic",
            'state' => $this->csrfTokenManager->getToken('wordpress-oauth')->getValue()
        ]);

        return new RedirectResponse($url.'?'.$query_string);
    }

    #[Route("/login/activate/{token}", name: 'app_activate')]
    public function activate(Request $request,$token)
    {
        $user = $this->userRepository->findOneBy(array('confirmation_token'=>$token));
        $session = $request->getSession();
        if ($user){
            $user->setIsActive(true);
            $user->setConfirmationToken(null);
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
            $session->getFlashBag()->add('success', 'Votre compte a bien été activé, bienvenu 🙂');
        }else{
            $session->getFlashBag()->add('warning', 'Aucun utilisateur associé à cette clef 😥');
        }
        return $this->redirectToRoute('app_login');
    }

    /**
     *
     * @Route("/login/reset_password/{token}", name="app_reset_password")
     * @param Request $request
     * @param $token
     * @param UserPasswordEncoderInterface $passwordEncoder
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     */
    public function resetPassword(Request $request,$token,UserPasswordEncoderInterface $passwordEncoder)
    {
        $user = $this->userRepository->findOneBy(array('rp_token'=>$token));
        $session = $request->getSession();
        if (!$user){
            $session->getFlashBag()->add('warning', 'Aucun utilisateur associé à cette clef 😥');
            return $this->redirectToRoute('app_login');
        }
        $now = new \DateTime('now');
        if ($now > date_add($user->getRpTokenCreatedAt(),date_interval_create_from_date_string('1 day'))){
            $user->setRpTokenCreatedAt(null);
            $user->setRpToken(null);
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();
            $session->getFlashBag()->add('error', 'Cette url a expirée 😿');
            return $this->redirectToRoute('app_login');
        }
        if ($request->isMethod('POST')) {
            $token = new CsrfToken('reset_password', $request->request->get('_csrf_token'));
            if (!$this->csrfTokenManager->isTokenValid($token)) {
                throw new InvalidCsrfTokenException();
            }
            if ($request->request->get('password')===$request->request->get('password_bis')){
                $user->setPassword($passwordEncoder->encodePassword(
                    $user,
                    $request->request->get('password')
                ));
                $user->setRpTokenCreatedAt(null);
                $user->setRpToken(null);
                $em = $this->getDoctrine()->getManager();
                $em->persist($user);
                $em->flush();
                $session->set(Security::LAST_USERNAME, $user->getUsername());
                $session->getFlashBag()->add('success', 'Mot de passe changé ! 💪');
            }else{
                $session->getFlashBag()->add('error', 'Oups, il semble que tu n\'ai pas tapé deux fois la même chose ? 😞');
                return $this->render('security/reset_password.html.twig',array('user'=>$user));
            }
            return $this->redirectToRoute('app_login');
        }
        return $this->render('security/reset_password.html.twig',array('user'=>$user));
    }

    #[Route("/login/forgot_password", name: 'app_forgot_password')]
    public function forgotPassword(Request $request)
    {
        if ($request->isMethod('POST')) {
            $token = new CsrfToken('forgot_password', $request->request->get('_csrf_token'));
            if (!$this->csrfTokenManager->isTokenValid($token)) {
                throw new InvalidCsrfTokenException();
            }
            $email_or_username = $request->request->get('email_or_username');
            $session = $request->getSession();
            if (!$email_or_username){
                $session->getFlashBag()->add('error', 'please provide a username or email');
                return $this->redirectToRoute('app_forgot_password');
            }
            $user = $this->userRepository->findOneByEmailOrUsername($email_or_username);
            if ($user){
                $user->generateRpToken();
                $em = $this->getDoctrine()->getManager();
                $em->persist($user);
                $em->flush();
                if (!$this->_sendForgotPassword($user,$session)){
                    return $this->redirectToRoute('app_forgot_password');
                }
            }
            if (strpos($email_or_username,'@')===false){
                $session->getFlashBag()->add('success', 'Si un utilisateur est bien associé à ce pseudo, un email vient de lui être envoyé 😉');
            }else{
                $session->getFlashBag()->add('success', 'Si un utilisateur existe avec cet email, un email vient de lui être envoyé 😉');
            }
            return $this->redirectToRoute('app_login');
        }
        return $this->render('security/forgot_password.html.twig');
    }

    /**
     * @param User $user
     * @param SessionInterface $session
     * @return int
     */
    private function _sendForgotPassword(User $user,SessionInterface $session){
        if ($e = $this->mailer->sendMail($user->getEmail(),'Mot de passe oublié ?','forgot_password',['user'=>$user])){
            $session->getFlashBag()->add('error', 'oups, l\'email de rappel na pas pu être envoyé.'.
                ' On réessaie ensemble dans un moment ?');
            $session->getFlashBag()->add('warning', $e->getMessage());
            return 0;
        }
    }

    /**
     * @param User $user
     * @param SessionInterface $session
     * @param int $count
     * @return int
     */
    private function _sendConfirm(User $user,SessionInterface $session,int $count = 0){
        if ($e = $this->mailer->sendMail($user->getEmail(),'Confirme ton nouveau compte','confirm',['user' => $user,])){
            $session->getFlashBag()->add('error', 'oups, l\'email de confirmation na pas pu être envoyé.'.
                ' On réessaie ensemble dans un moment ?');
            $session->getFlashBag()->add('warning', $e->getMessage());
            return 0;
        }
        return 1;
    }



    #[Route("/register", name: 'app_register')]
    public function register(Request $request, UserPasswordEncoderInterface $passwordEncoder)
    {

        $register_code = $this->config->getValue('app/register_code');
        if ($request->isMethod('POST')) {

            $em = $this->getDoctrine()->getManager();
            $session = $request->getSession();

            $username = $request->request->get('username');
            $email = $request->request->get('email');
            $exist = $em->getRepository(User::class)->findOneBy(array('username'=>$username));
            if ($exist){

templates/security/forgot_password.html.twig
{% block title %}Oups, un trou de mémoire ?{% endblock %}
{% extends 'base.html.twig' %}
{% block body %}
    <div class="grid grid-cols-3 gap-4">
        <div class=""></div>
        <form action="{{ path('app_forgot_password') }}" method="post" class="login">
            <h1>Mot de passe oublié ?</h1>
            <input type="hidden" name="_csrf_token" value="{{ csrf_token('forgot_password') }}" >
            <input type="text" id="email_or_username" name="email_or_username" value="" placeholder="Nom d'utilisateur ou email" required/><br>
            <button type="submit" class="my-4 btn btn--primary">Demander un nouveau mot de passe</button>
        </form>
    </div>
{% endblock %}

templates/security/login.html.twig
{% block title %}Connecte toi :){% endblock %}
{% extends 'base.html.twig' %}
{% block body %}
    <div class="flex items-center justify-center my-8 p-0 md:p-5">
        <div class="md:p-10 p-2 mx-auto md:w-full md:max-w-md">
            <div class="bg-white shadow w-full rounded-xl divide-y divide-gray-200">
                <div class="px-5 py-7">
                    <div class="w-full text-center mb-5">
                        <img src="{{ asset('build/img/login.svg') }}" alt="login" class="w-1/3 lg:w-1/4 inline">
                    </div>
                    <form action="{{ path('app_login') }}" method="post" class="login col-2">
                        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}" >
                        <div class="flex -mx-3">
                            <div class="w-full px-3 mb-3">
                                <label for="password">E-mail ou nom d'utilisateur</label>
                                <div class="flex">
                                    <div class="ico">{{ mdi('account-outline') }}</i></div>
                                    <input type="text" id="username" name="_username" value="{{ last_username }}" class="outline-none iconed" placeholder="Rob1913"/>
                                </div>
                            </div>
                        </div>
                        <div class="flex -mx-3">
                            <div class="w-full px-3 mb-3">
                                <label for="password">Mot de passe</label>
                                <div class="flex">
                                    <div class="ico">{{ mdi('lock-outline') }}</div>
                                    <input required type="password" id="password" name="_password" placeholder="************" class="outline-none iconed">
                                </div>
                            </div>
                        </div>
                        <label>
                            <input type="checkbox" class="checkbox border rounded-lg" value="_remember_me"> Se souvenir de moi
                        </label>
                        <button type="submit" class="btn btn--success w-full cursor-pointer">
                            Login 
                            {# <div class="ico">{{ mdi('arrow-right') }}</div> #}
                        </button>
                    </form>
                </div>
                {# <div class="py-5 text-center">
                    <a href="{{ path('app_oauth') }}" class="btn btn--warning">{{ config('app/oauth_text') }}</a>
                </div> #}
                <div class="py-5">
                    <div class="grid grid-cols-2 gap-1">
                        <div class="text-center sm:text-left whitespace-nowrap">
                            <a href="{{ path('app_forgot_password') }}" class="transition duration-200 mx-5 px-5 py-4 cursor-pointer font-normal text-sm rounded-lg text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-200 focus:ring-2 focus:ring-gray-400 focus:ring-opacity-50 ring-inset">
                                <i class="mdi mdi-lock-open-outline"></i>
                                <span class="inline-block ml-1">Mot de passe oublié ?</span>
                            </a>
                        </div>
                        <div class="text-center sm:text-right  whitespace-nowrap">
    {#                        <button class="transition duration-200 mx-5 px-5 py-4 cursor-pointer font-normal text-sm rounded-lg text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-200 focus:ring-2 focus:ring-gray-400 focus:ring-opacity-50 ring-inset">#}
    {#                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="w-4 h-4 inline-block align-text-bottom	">#}
    {#                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 5.636l-3.536 3.536m0 5.656l3.536 3.536M9.172 9.172L5.636 5.636m3.536 9.192l-3.536 3.536M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-5 0a4 4 0 11-8 0 4 4 0 018 0z" />#}
    {#                            </svg>#}
    {#                            <span class="inline-block ml-1">Help</span>#}
    {#                        </button>#}
                        </div>
                    </div>
                </div>
            </div>
            <div class="py-5">
                <div class="grid grid-cols-2 gap-1">
                    <div class="text-center sm:text-left whitespace-nowrap">
                        <button data-href="/" class="transition duration-200 mx-5 px-5 py-2.5 cursor-pointer font-normal text-sm rounded-lg text-gray-500 hover:bg-gray-200 focus:outline-none focus:bg-gray-300 focus:ring-2 focus:ring-gray-400 focus:ring-opacity-50 ring-inset">
                            <i class="mdi mdi-arrow-left ml-1"></i> Retour
                        </button>
                    </div>
                    <div class="text-right">
                        <a class="btn btn--primary" href="{{ path('app_register') }}"><i class="mdi mdi-plus-circle mr-1"></i>créer un compte</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/security/register.html.twig
{% extends 'base.html.twig' %}
{% block title %}Je rejoins la communauté{% endblock %}
{% block body %}
    <div class="min-w-screen min-h-screen flex items-center justify-center px-5 py-5">
        <div class="bg-gray-100 text-gray-500 rounded-xl shadow-xl w-full overflow-hidden" style="max-width:1000px">
            <div class="md:flex w-full">
                <div class="hidden md:block w-1/2 bg-indigo-500 py-10 px-10">
                    <img src="{{ asset('build/img/register.svg') }}" alt="register" class="w-full">
                </div>
                <div class="w-full md:w-1/2 py-10 px-5 md:px-10">
                    <div class="w-full px-3 mb-5 text-center">
                        <a href="{{ path('app_oauth') }}" class="btn btn--warning">{{ config('app/oauth_text') }}</a>
                    </div>
                    <div class="w-full text-center text-gray-500 text-xl my-4">
                        <div class="h-3 border-b"></div>
                        <div class="-mt-3 h-6 leading-6 bg-gray-100 mx-auto w-8">ou</div>
                    </div>
                    <div class="text-center mb-5">
                        <h1 class="font-bold text-3xl text-gray-900">Créer un compte</h1>
                        <p>Saisis tes informations pour t'inscrire</p>
                    </div>
                    <form method="post" class="register">
                        <div class="flex -mx-3">
                            <div class="w-full px-3 mb-5">
                                <label for="" >Nom d'utilisateur</label>
                                <div class="flex">
                                    <div class="ico"><i class="mdi mdi-account-outline"></i></div>
                                    <input autofocus required name="username" type="text" class="outline-none" placeholder="Rob1913">
                                </div>
                            </div>
                        </div>
                        <div class="flex -mx-3">
                            <div class="w-full px-3 mb-5">
                                <label for="">Email</label>
                                <div class="flex">
                                    <div class="ico"><i class="mdi mdi-email-outline"></i></div>
                                    <input required type="email" name="email" class="outline-none" placeholder="robert@hart.org">
                                </div>
                            </div>
                        </div>
                        <div class="flex -mx-3">
                            <div class="w-full px-3 {% if use_register_code %}mb-5{% else %}mb-12{% endif %}">
                                <label for="password">Mot de passe</label>
                                <div class="flex">
                                    <div class="ico"><i class="mdi mdi-lock-outline"></i></div>
                                    <input required name="password" id="password" type="password" class="outline-none" placeholder="************">
                                </div>
                            </div>
                        </div>
                        {% if use_register_code %}
                            <div class="flex -mx-3">
                                <div class="w-full px-3 mb-12">
                                    <label for="" class="text-xs font-semibold px-1">Mon code d'accès</label>
                                    <div class="flex">
                                        <div class="ico"><i class="mdi mdi-key-variant"></i></div>
                                        <input required name="code" type="text" class="outline-none" placeholder="Sesamum_indicum">
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                        <div class="flex -mx-3">
                            <div class="w-full px-3 mb-5 text-center">
                                <button type="submit" class="btn btn--primary">Je rejoins la communauté</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/security/reset_password.html.twig
{% block title %}Ca arrive à tout le monde ;){% endblock %}
{% extends 'base.html.twig' %}
{% block body %}
    <div class="grid-6-small-2">
        <div class="col-2"></div>
        <form action="{{ path('app_reset_password',{'token':user.rpToken}) }}" method="post" class="login col-2">
            <h1>Bonjour {{ user.username }} ! </h1>
            <h2>Changeons ce fichu mot de passe !</h2>
            <input type="hidden" name="_csrf_token" value="{{ csrf_token('reset_password') }}" >
            <input type="password" id="password" name="password" value="" placeholder="Nouveau mot de passe" required/><br>
            <input type="password" id="password_bis" name="password_bis" value="" placeholder="Une seconde fois" required/><br>
            <button type="submit" class=" btn btn--primary">Changer mon mot de passe</button>
        </form>
    </div>
{% endblock %}