src/Entity/Plant.php
<?php

namespace App\Entity;

use App\Repository\PlantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlantRepository::class)]
#[ORM\Table(name: 'plant')]
#[ORM\Index(columns:["latin_name", "name"], flags:["fulltext"])]
class Plant
{

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private int $id;

    #[ORM\Column(length: 50)]
    private string $latin_name;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $rusticity = null;

    #[ORM\Column(length: 100)]
    private ?string $rusticity_comment = null;

    #[ORM\Column]
    private ?int $temperature = null;

    #[ORM\Column(type:Types::SMALLINT)]
    private ?int $woody = null;

    #[ORM\Column()]
    private ?int $min_height = null;

    #[ORM\Column()]
    private ?int $max_height = null;

    #[ORM\Column()]
    private ?int $min_width = null;

    #[ORM\Column()]
    private ?int $max_width = null;

    #[ORM\Column()]
    private ?int $min_sexual_maturity = null;

    #[ORM\Column()]
    private ?int $max_sexual_maturity = null;

    #[ORM\Column(length:200)]
    private ?string $native_place = null;

    #[ORM\Column(length:500)]
    private ?string $botany_leaf = null;

    #[ORM\Column(length:500)]
    private ?string $botany_branch = null;

    #[ORM\Column(length:500)]
    private ?string $botany_root = null;

    #[ORM\Column(length:500)]
    private ?string $botany_flower = null;

    #[ORM\Column(length:500)]
    private ?string $botany_fruit = null;

    #[ORM\Column(length:500)]
    private ?string $botany_seed = null;

    #[ORM\Column(length:20)]
    private ?string $density = null;

    #[ORM\Column(type:Types::TEXT)]
    private ?string $interest = null;

    #[ORM\Column(length:100)]
    private ?string $specificity = null;

    /**
     * todo: user real user or entity
     */
    #[ORM\Column(length: 100)]
    private ?string $author = null;

    #[ORM\ManyToOne(targetEntity: PlantFamily::class,inversedBy : "plants")]
    private $family;

    #[ORM\OneToMany(targetEntity: Source::class,mappedBy : "plant",orphanRemoval: true)]
    private $sources;


    #[ORM\ManyToMany(targetEntity: AttributeValue::class,mappedBy : "plants")]
    private $attributes_values;

    private $_attributes_by_code;

    
    #[ORM\OneToMany(targetEntity: Image::class,mappedBy : "plant",orphanRemoval: true,cascade: ['persist'])]
    private $images;

    public function __construct()
    {
        $this->sources = new ArrayCollection();
        $this->attributes_values = new ArrayCollection();
        $this->_attributes_by_code = array();
        $this->images = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLatinName(): ?string
    {
        return $this->latin_name;
    }

    public function setLatinName(string $latin_name): self
    {
        $this->latin_name = $latin_name;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): string
    {
        return self::makeSlug($this->getLatinName());
    }

    static function makeSlug($string,$length = 50){
        //Lower case everything
        $string = strtolower($string);
        //remove accent
        $unwanted_array = array(    'Š'=>'S', 'š'=>'s', 'Ž'=>'Z', 'ž'=>'z', 'À'=>'A', 'Á'=>'A', 'Â'=>'A', 'Ã'=>'A', 'Ä'=>'A', 'Å'=>'A', 'Æ'=>'A', 'Ç'=>'C', 'È'=>'E', 'É'=>'E',
            'Ê'=>'E', 'Ë'=>'E', 'Ì'=>'I', 'Í'=>'I', 'Î'=>'I', 'Ï'=>'I', 'Ñ'=>'N', 'Ò'=>'O', 'Ó'=>'O', 'Ô'=>'O', 'Õ'=>'O', 'Ö'=>'O', 'Ø'=>'O', 'Ù'=>'U',
            'Ú'=>'U', 'Û'=>'U', 'Ü'=>'U', 'Ý'=>'Y', 'Þ'=>'B', 'ß'=>'Ss', 'à'=>'a', 'á'=>'a', 'â'=>'a', 'ã'=>'a', 'ä'=>'a', 'å'=>'a', 'æ'=>'a', 'ç'=>'c',
            'è'=>'e', 'é'=>'e', 'ê'=>'e', 'ë'=>'e', 'ì'=>'i', 'í'=>'i', 'î'=>'i', 'ï'=>'i', 'ð'=>'o', 'ñ'=>'n', 'ò'=>'o', 'ó'=>'o', 'ô'=>'o', 'õ'=>'o',
            'ö'=>'o', 'ø'=>'o', 'ù'=>'u', 'ú'=>'u', 'û'=>'u', 'ý'=>'y', 'þ'=>'b', 'ÿ'=>'y' );
        $string = strtr( $string, $unwanted_array );
        //Make alphanumeric (removes all other characters)
        $string = preg_replace("/[^a-z0-9+_\s-]/", "", $string);
        //Clean up multiple dashes or whitespaces
        $string = preg_replace("/[\s-]+/", " ", $string);
        //Convert whitespaces and underscore to dash
        $string = preg_replace("/[\s_]/", "-", $string);
        //shorten
        $string = substr($string,0,$length);
        return $string;
    }

    public function getRusticity(): ?int
    {
        return $this->rusticity;
    }

    public function setRusticity(?int $rusticity): self
    {
        $this->rusticity = $rusticity;

        return $this;
    }

    public function getRusticityComment(): ?string
    {
        return $this->rusticity_comment;
    }

    public function setRusticityComment(?string $rusticity_comment): self
    {
        $this->rusticity_comment = $rusticity_comment;

        return $this;
    }

    public function getTemperature(): ?int
    {
        return $this->temperature;
    }

    public function setTemperature(?int $temperature): self
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getWoody(): ?bool
    {
        return $this->woody;
    }

    public function setWoody(?int $woody): self
    {
        $this->woody = $woody;

        return $this;
    }

    public function getMinHeight(): ?int
    {
        return $this->min_height;
    }

    public function setMinHeight(?int $min_height): self
    {
        $this->min_height = $min_height;

        return $this;
    }

    public function getMaxHeight(): ?int
    {
        return $this->max_height;
    }

    public function setMaxHeight(?int $max_height): self
    {
        $this->max_height = $max_height;

        return $this;
    }

    public function getHeight(): string
    {
        if ($this->min_height === null){
            if ($this->max_height === null) {
                return '';
            }
        }
        if ($this->max_height === null) {
            return $this->min_height;
        }
        if ($this->min_height == $this->max_height)
            return $this->min_height;
        return $this->min_height.'-'.$this->max_height;
    }

    public function getMinWidth(): ?int
    {
        return $this->min_width;
    }

    public function setMinWidth(int $min_width): self
    {
        $this->min_width = $min_width;

        return $this;
    }

    public function getMaxWidth(): ?int
    {
        return $this->max_width;
    }

    public function setMaxWidth(?int $max_width): self
    {
        $this->max_width = $max_width;

        return $this;
    }

    public function getWidth(): string
    {
        if ($this->min_width === null){
            if ($this->max_width === null) {
                return '';
            }
        }
        if ($this->max_width === null) {
            return $this->min_width;
        }
        if ($this->min_width == $this->max_width)
            return $this->min_width;
        return $this->min_width.'-'.$this->max_width;
    }

    public function getMinSexualMaturity(): ?int
    {
        return $this->min_sexual_maturity;
    }

    public function setMinSexualMaturity(?int $min_sexual_maturity): self
    {
        $this->min_sexual_maturity = $min_sexual_maturity;

        return $this;
    }

    public function getMaxSexualMaturity(): ?int
    {
        return $this->max_sexual_maturity;
    }

    public function setMaxSexualMaturity(?int $max_sexual_maturity): self
    {
        $this->max_sexual_maturity = $max_sexual_maturity;

        return $this;
    }

    public function getNativePlace(): ?string
    {
        return $this->native_place;
    }

    public function setNativePlace(?string $native_place): self
    {
        $this->native_place = $native_place;

        return $this;
    }

    public function getBotanyLeaf(): ?string
    {
        return $this->botany_leaf;
    }

    public function setBotanyLeaf(?string $botany_leaf): self
    {
        $this->botany_leaf = $botany_leaf;

        return $this;
    }

    public function getBotanyBranch(): ?string
    {
        return $this->botany_branch;
    }

    public function setBotanyBranch(?string $botany_branch): self
    {
        $this->botany_branch = $botany_branch;

        return $this;
    }

    public function getBotanyRoot(): ?string
    {
        return $this->botany_root;
    }

    public function setBotanyRoot(?string $botany_root): self
    {
        $this->botany_root = $botany_root;

        return $this;
    }

    public function getBotanyFlower(): ?string
    {
        return $this->botany_flower;
    }

    public function setBotanyFlower(?string $botany_flower): self
    {
        $this->botany_flower = $botany_flower;

        return $this;
    }

    public function getBotanyFruit(): ?string
    {
        return $this->botany_fruit;
    }

    public function setBotanyFruit(?string $botany_fruit): self
    {
        $this->botany_fruit = $botany_fruit;

        return $this;
    }

    public function getBotanySeed(): ?string
    {
        return $this->botany_seed;
    }

    public function setBotanySeed(?string $botany_seed): self
    {
        $this->botany_seed = $botany_seed;

        return $this;
    }

    public function getDensity(): ?string
    {
        return $this->density;
    }

    public function setDensity(?string $density): self
    {
        $this->density = $density;

        return $this;
    }

    public function getInterest(): ?string
    {
        return $this->interest;
    }

    public function setInterest(?string $interest): self
    {

src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PropertyRepository::class)]
#[ORM\Table(name: 'property')]
class Property extends PropertyOrAttribute
{

    public function isProperty(): bool
    {
        return true;
    }

    public function getTemplates(string $type = 'line'){
        $filename = "property/_partial/".$this->getCode()."_".$type.".html.twig";
        $default = "property/_partial/default_".$type.".html.twig";
        return array($filename,$default);
    }

    public function getEditTemplates(string $type = 'line'){
        $filename = "property/_partial/".$this->getCode()."_".$type."_edit.html.twig";
        $default = "property/_partial/default_".$type."_edit.html.twig";
        return array($filename,$default);
    }

    public static function camelCase($string, $dontStrip = []){
        /*
         * This will take any dash or underscore turn it into a space, run ucwords against
         * it so it capitalizes the first letter in all words separated by a space then it
         * turns and deletes all spaces.
         */
        return lcfirst(str_replace('_', '', ucwords(preg_replace('/^a-z0-9'.implode('',$dontStrip).']+/', '_',$string))));
    }

}

templates/property/_partial/default_edit.html.twig
{#<form action="{{ path('plant_property_edit',{'id':plant.id,'code':property.code}) }}" onsubmit="return propertyLineEditSubmit(this)">#}
{#    <input type="hidden" name="_csrf_token" value="{{ csrf_token('plant_property_edit_'~property.code) }}" >#}
{#    <b>{{ property.name }} :</b><input type="text" value="{{ plant | get(property.code) }}" name="{{ property.code }}">#}
{#    <input type="submit" value="Ok">#}
{#</form>#}

templates/property/_partial/flowerings_crops_block.html.twig
{% set flowerings = plant.getAttributeValuesByCodeAsArray('flowering') %}
{% set crops = plant.getAttributeValuesByCodeAsArray('crop') %}
{% set months = ['j','f','m','a','m','j','j','a','s','o','n','d'] %}
{% if flowerings | length or crops | length %}
        <div class="grid grid-flow-col">
            <div class="col-span-2 flex items-center gap-4">
                <div class="bg-img bg-contain bg-no-repeat bg-center h-5 w-5" style="--bg-image: url({{ asset('build/img/picto/fleur.svg') }})" ></div>
                <div>Floraison</div>
            </div>
            {% for m in 1..12 %}
                <div class="text-center">
                    {% if flowerings[m] is defined %}
                        <a class="capitalize font-bold text-black" href="{{ path('plant_index',{'a_flowering[]':flowerings[m].id}) }}">{{ months[m-1] }}</a>
                    {% else %}
                        <span class="capitalize text-gray-300">{{ months[m-1] }}</span>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <div class="grid grid-flow-col">
            <div class="col-span-2 flex items-center gap-4">
                <div class="bg-img bg-contain bg-no-repeat bg-center h-5 w-5" style="--bg-image: url({{ asset('build/img/picto/fructif.svg') }})" ></div>
                <div>Fructification</div>
            </div>
            {% for m in 1..12 %}
                <div class="text-center">
                    {% if crops[m] is defined %}
                        <a class="capitalize font-bold text-black" href="{{ path('plant_index',{'a_crops[]':crops[m].id}) }}">{{ months[m-1] }}</a>
                    {% else %}
                        <span class="capitalize text-gray-300">{{ months[m-1] }}</span>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
{% endif %}

templates/property/_partial/flowerings_crops_edit.html.twig
<div data-code="{{ element.code }}" data-type="property" data-id="{{ element.id }}" class="border-b" >
    {% set flowerings = plant.getAttributeValuesByCodeAsArray('flowering') %}
    {% set crops = plant.getAttributeValuesByCodeAsArray('crop') %}
    <form action="{{ path('plant_flowerings_crops_edit',{'id':plant.id}) }}" onsubmit="return false;">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('plant_flowerings_crops_edit') }}" >
        <table class="flowerings_crops mx-auto">
            <thead>
                <tr>
                    <th colspan="12">Floraison</th>
                </tr>
            </thead>
            <tbody>
            <tr>
                <td class="w-1/12 text-center">J</td>
                <td class="w-1/12 text-center">F</td>
                <td class="w-1/12 text-center">M</td>
                <td class="w-1/12 text-center">A</td>
                <td class="w-1/12 text-center">M</td>
                <td class="w-1/12 text-center">J</td>
                <td class="w-1/12 text-center">J</td>
                <td class="w-1/12 text-center">A</td>
                <td class="w-1/12 text-center">S</td>
                <td class="w-1/12 text-center">O</td>
                <td class="w-1/12 text-center">N</td>
                <td class="w-1/12 text-center">D</td>
            </tr>
            <tr>
                {% for m in 1..12 %}
                    <td class="w-1/12">
                        <label for="value_for_flowerings_{{ m }}" class="checkbox{% if flowerings[m] is defined %} checked{% endif %} w-5 h-5 block text-center overflow-hidden">
                            <i class="text-sm mdi mdi mdi-flower-poppy checked"></i>
                            <i class="text-sm mdi mdi mdi-circle-small unchecked"></i>
                            <input id="value_for_flowerings_{{ m }}" type="checkbox" name="flowerings[{{ m }}]" value="1" {% if flowerings[m] is defined %}checked="checked"{% endif %}>
                        </label>
                    </td>
                {% endfor %}
            </tr>
            </tbody>
        </table>
        <table  class="flowerings_crops  mx-auto">
            <thead>
                <tr>
                    <th colspan="12">Fructification</th>
                </tr>
            </thead>
            <tbody>
            <tr>
                <td class="w-1/12 text-center">J</td>
                <td class="w-1/12 text-center">F</td>
                <td class="w-1/12 text-center">M</td>
                <td class="w-1/12 text-center">A</td>
                <td class="w-1/12 text-center">M</td>
                <td class="w-1/12 text-center">J</td>
                <td class="w-1/12 text-center">J</td>
                <td class="w-1/12 text-center">A</td>
                <td class="w-1/12 text-center">S</td>
                <td class="w-1/12 text-center">O</td>
                <td class="w-1/12 text-center">N</td>
                <td class="w-1/12 text-center">D</td>
            </tr>
                <tr>
                    {% for m in 1..12 %}
                        <td class="w-1/12">
                            <label for="value_for_crops_{{ m }}" class="checkbox{% if crops[m] is defined %} checked{% endif %} w-5 h-5 block text-center overflow-hidden">
                                <i class="text-sm mdi mdi mdi-fruit-cherries checked"></i>
                                <i class="text-sm mdi mdi mdi-circle-small unchecked"></i>
                                <input id="value_for_crops_{{ m }}" type="checkbox" name="crops[{{ m }}]" value="1" {% if crops[m] is defined %}checked="checked"{% endif %}>
                            </label>
                        </td>
                    {% endfor %}
                </tr>
            </tbody>
        </table>
    </form>
</div>

templates/property/_partial/flowerings_crops_line.html.twig
{% if flowerings | length or crops | length %}
    <table class="flowerings_crops">
        <thead>
        <tr>
            <th></th>
            <th>Jan</th>
            <th>Fév</th>
            <th>Mar</th>
            <th>Avr</th>
            <th>Mai</th>
            <th>Juin</th>
            <th>Juil</th>
            <th>Aout</th>
            <th>Sept</th>
            <th>Oct</th>
            <th>Nov</th>
            <th>Déc</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>Floraison</td>
            {% for m in 1..12 %}
                <td>
                    {% if flowerings[m] is defined %}<a href="{{ path('plant_index',{'a_flowering[]':flowerings[m].id}) }}">🌼</a>{% endif %}
                </td>
            {% endfor %}
        </tr>
        <tr>
            <td>Fructif</td>
            {% for m in 1..12 %}
                <td>
                    {% if crops[m] is defined %}<a href="{{ path('plant_index',{'a_crop[]':crops[m].id}) }}">🍎</a>{% endif %}
                </td>
            {% endfor %}
        </tr>
        </tbody>
    </table>
{% endif %}

templates/property/_partial/gallery_line.html.twig
{% if plant.images | length %}
    <div class="flex flex-wrap justify-start">
        {% for image in plant.images %}
            {% if (loop.index != 1) or (hide_first != 1) %}
                <a href="{{ asset(image.src) }}" data-fslightbox class="block flex-none"><img class="border-2 border-white shadow-lg m-2 h-24 w-24" src="{{ asset(image.src)|imagine_filter('square') }}" alt=""></a>
            {% endif %}
        {% endfor %}
    </div>
{% else %}
    <span style="color:orange;">Aucune image associée</span>
{% endif %}

templates/property/_partial/gallery_main_image.html.twig
{% if plant is not null and 
    plant.images | length %}
    {% set image = plant.images.first %}
    <a href="{{ asset(image.src)|imagine_filter('card') }}" data-fslightbox class="block w-full h-full bg-cover bg-img border-4 border-white shadow-lg" style="--bg-image: url({{ asset(image.src) }})">
    </a>
{% else %}

{% endif %}

templates/property/_partial/height_width_edit.html.twig
<div data-code="{{ property.code }}" data-type="property" data-id="{{ property.id }}" class="border-b" >
    <form action="{{ path('plant_property_edit',{'id':plant.id,'code':property.code}) }}" onsubmit="return false;" class="seamless">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('plant_property_edit_'~property.code) }}" >
        <div>
            hauteur : <input style="width: 60px" type="text" data-type="digit" value="{{ plant.minHeight }}" name="min_height">-<input style="width: 60px" type="text" data-type="digit" value="{{ plant.maxHeight }}" name="max_height">m
            <br>
            largeur : <input style="width: 60px" type="text" data-type="digit" value="{{ plant.minWidth }}" name="min_width">-<input style="width: 60px" type="text" data-type="digit" value="{{ plant.maxWidth }}" name="max_width">m
        </div>
    </form>
</div>

templates/property/_partial/height_width_line.html.twig
<div data-code="{{ element.code }}" data-type="property" data-id="{{ element.id }}" class="show">
    <img src="{{ asset('build/img/picto/hauteur.svg') }}" alt="" class="h-14 inline align-baseline -mb-2"> {{ plant.Height }}m
    <img src="{{ asset('build/img/picto/largeur.svg') }}" alt="" class="w-14 inline align-baseline -mb-2"> {{ plant.Width }}m
</div>

templates/property/_partial/rusticity_edit.html.twig
<div data-code="{{ element.code }}" data-type="property" data-id="{{ element.id }}" class="border-b p-1" >
    <form action="{{ path('plant_property_edit',{'id':plant.id,'code':property.code}) }}" onsubmit="return false;">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('plant_property_edit_'~property.code) }}" >
        {{ property.name }} : <input type="number" value="{{ plant | get(property.code) }}" name="{{ property.code }}" class="text-right w-10">°C
    </form>
</div>

templates/property/_partial/rusticity_filter.html.twig
<h4>Rusticité</h4>
<div class="content">
    <input type="range" id="rusticity_v" name="rusticity_v" min="-40" max="5" class="f_not_used" disabled="disabled" value="{% if ( filters['rusticity'] is defined ) %}{{filters['rusticity']}}{% endif %}">
    <br>
    <label class="inline-flex items-center mt-3 cursor-pointer" for="rusticity">
        <input id="rusticity" name="rusticity" type="checkbox" class="form-checkbox h-5 w-5 text-blue-600" value="" data-f-value="" {% if ( filters['rusticity'] is defined ) %}checked="checked"{% endif %} >
        <div class="ml-2 text-gray-700 label">Rusticité <span></span>°C</div>
    </label>
    <script>
        document.getElementById('rusticity_v').addEventListener('change',function (){
            document.getElementById('rusticity').value = this.value;
            document.getElementById('rusticity').setAttribute('data-f-value',this.value);
            document.querySelector('[for="rusticity"] .label span').innerHTML = this.value;
        });
        document.getElementById('rusticity').addEventListener('click',function (){
            console.log(this);
            if (this.checked)
                document.getElementById('rusticity_v').removeAttribute("disabled");
            else
                document.getElementById('rusticity_v').setAttribute("disabled", "disabled");
        });
        document.getElementById('rusticity_v').dispatchEvent(new Event('change'));
    </script>
</div>

templates/property/_partial/rusticity_line.html.twig
<b>{{ property.name }} :</b> {{ plant.Rusticity }}°C

templates/property/_partial/sexual_maturity_line.html.twig
<div data-code="{{ element.code }}" data-type="property" data-id="{{ element.id }}" class="show">
    <span class="font-bold uppercase">{{ element.name }} : </span><span class="uppercase">{{ plant.MinSexualMaturity }}-{{ plant.MaxSexualMaturity }} ans</span>
</div>

templates/property/_partial/sources_edit.html.twig
<div id="sources" class="">
    <div data-code="source" data-type="property" data-id="0" class="border-b">
        <ul>
            {% for source in plant.sources %}
                <li class="my-1 h-10 block flex" id="source{{ source.id }}">
                    <form action="{{ path('plant_source_edit',{'id':plant.id,'source':source.id}) }}" onsubmit="return false;" class="seamless h-full flex-1 pl-2">
                        <input type="hidden" name="_csrf_token" value="{{ csrf_token('plant_source_edit_'~source.id) }}" >
                        <input type="text" value="{{ source.name }}" name="value" class="bg-transparent h-full text-sm w-full" />
                    </form>
                    <form action="{{ path('plant_source_delete',{'id':plant.id,'source':source.id}) }}" onsubmit="return false;" class="seamless h-full w-10 flex-shrink-0">
                        <input type="hidden" name="_csrf_token" value="{{ csrf_token('plant_source_delete_'~source.id) }}" >
                        <button type="submit" class="text-red-600 w-full h-10 hover:text-black" data-type="delete" data-target="#source{{ source.id }}"><i class="mdi mdi-trash-can"></i></button>
                    </form>
                </li>
            {% endfor %}
        </ul>
    </div>
    <form action="{{ path('plant_source_new',{'id':plant.id}) }}" onsubmit="return false;" class="seamless">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('plant_source_new') }}" >
        <div class="flex">
            <input type="text" value="" required="required" name="value" placeholder="https://..." class="w-full flex-1 flex-shrink-0 p-2" />
            <button type="submit" class="w-10 h-10 text-gray-100 bg-gray-800 hover:bg-gray-700" id="add_source" ><i class="mdi mdi-plus-box"></i></button>
        </div>
    </form>
</div>

templates/property/_partial/sources_line.html.twig
{% if plant.sources | length %}
    <div>
        <span class="uppercase font-bold">Sources : </span>
        <ul>
            {% for source in plant.sources %}
                <li class="hover:underline hover:text-blue-400">{{ source.name | autolink | raw }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}