src/Entity/Attribute.php
<?php

namespace App\Entity;

use App\Repository\AttributeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AttributeRepository::class)]
#[ORM\Table(name: 'attribute')]
class Attribute extends PropertyOrAttribute
{
    const TYPE_NONE  = 1;
    const TYPE_SINGLE  = 2;
    const TYPE_MULTIPLE = 3;
    const TYPE_UNIQUE = 4;

    #[ORM\Column]
    private ?int $type;

    #[ORM\OneToMany(targetEntity: AttributeValue::class,mappedBy : "attribute", orphanRemoval:true)]
    private $availableValues;

    #[ORM\OneToOne(targetEntity: MainValue::class,mappedBy: "attribute", cascade: ['persist','remove'])]
    private $mainValue;

    public function __construct()
    {
        parent::__construct();
        $this->availableValues = new ArrayCollection();
    }

    public function getType(): ?int
    {
        return $this->type;
    }

    public function setType(int $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function isTypeNone() : bool
    {
        return $this->getType() === self::TYPE_NONE;
    }

    public function isTypeUnique() : bool
    {
        return $this->getType() === self::TYPE_UNIQUE;
    }

    public function isTypeMultiple() : bool
    {
        return $this->getType() === self::TYPE_MULTIPLE;
    }

    /**
     * @return Collection|AttributeValue[]
     */
    public function getAvailableValues(): Collection
    {
        return $this->availableValues;
    }

    /**
     * @return Collection|AttributeValue[]
     */
    public function getAvailableMainValues(): Collection
    {
        return $this->availableValues->filter(function ($attribute_value) {
            return $attribute_value->getMainValue();
        });
    }

    /**
     * @return Collection|AttributeValue[]
     */
    public function getAvailableNonMainValues(): Collection
    {
        return $this->availableValues->filter(function ($attribute_value) {
            return !$attribute_value->getMainValue();
        });
    }

    public function addAvailableValue(AttributeValue $availableValue): self
    {
        if (!$this->availableValues->contains($availableValue)) {
            $this->availableValues[] = $availableValue;
            $availableValue->setAttribute($this);
        }

        return $this;
    }

    public function removeAvailableValue(AttributeValue $availableValue): self
    {
        if ($this->availableValues->contains($availableValue)) {
            $this->availableValues->removeElement($availableValue);
            // set the owning side to null (unless already changed)
            if ($availableValue->getAttribute() === $this) {
                $availableValue->setAttribute(null);
            }
        }

        return $this;
    }

    public function getMainValue(): ?MainValue
    {
        return $this->mainValue;
    }

    public function setMainValue(MainValue $mainValue): self
    {
        $this->mainValue = $mainValue;

        // set the owning side of the relation if necessary
        if ($mainValue->getAttribute() !== $this) {
            $mainValue->setAttribute($this);
        }

        return $this;
    }

    public function isAttribute(): bool
    {
        return true;
    }

    public function getTemplates(string $type = 'line'){
        $filename = "attribute/_partial/".$this->getCode()."_".$type.".html.twig";
        $default = "attribute/_partial/default_".$type.".html.twig";
        return array($filename,$default);
    }

}

templates/attribute/_partial/besoin_zonage_block.html.twig
<span class="attrtitle">Zonage</span>
<div class="text-center" data-code="{{ element.code }}" data-type="attribute" data-id="{{ element.id }}" >
    <img class="inline-block h-16 w-16" src="{{ asset('build/img/picto/zone.svg') }}" alt=""><br>
    {% set min = 0 %}
    {% set max = 0 %}
    {% for attribute_value in plant.attributeValuesByCode(element.code) %}
        {% if min == 0 %}
            {% set min = attribute_value.value %}
        {% endif %}
        {% if attribute_value.value > max %}
            {% set max = attribute_value.value %}
        {% endif %}
    {% endfor %}
    zone {{ min }}-{{ max }}
</div>

templates/attribute/_partial/default_edit.html.twig
<div data-code="{{ element.code }}" data-type="attribute" data-id="{{ element.id }}" class="border-b" >
    <h6 class="bg-gray-200 text-black p-1 w-full text-center">{{ element.name }}</h6>
    <form action="{{ path('plant_attribute_edit',{'id':plant.id,'attribute':element.id}) }}" onsubmit="return false" class="seamless p-1">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('plant_attribute_edit_'~element.code) }}" >
        {% if element.typeNone %}{# checkbox #}
            {% set checked = plant.attributeValuesByCode(element.code) | length  %}
            <label for="value_for_{{ element.code }}" class="checkbox{% if checked %} checked{% endif %}">
                <input id="value_for_{{ element.code }}" type="checkbox" {% if checked %}checked="checked"{% endif %} name="value" value="{{ element.code }}">
                &nbsp;Oui
            </label>
        {% else %}
            <div class="">
            {% if element.mainValue is not null %}
                <span class="">{{ element.mainValue.label }}</span> :<br>
                {% if element.typeUnique %}
                    <textarea name="main_value" class="w-full bg-transparent">
                        {% if attribute_value %}{{ attribute_value.value }}{% endif %}
                    </textarea>
                {% else %}
                    {% set attribute_values = plant.mainAttributeValuesByCode(element.code) %}
                    {% if not element.typeMultiple %}
                        {% for value in element.availableMainValues %}
                            {% set checked = (value in attribute_values) and (value.mainValue is not null) %}
                            <label for="value_for_{{ element.code }}_{{ value.id }}" class="radio{% if checked %} checked{% endif %}">
                                <input id="value_for_{{ element.code }}_{{ value.id }}" type="radio" name="main_value" value="{{ value.id }}" {% if checked %}checked="checked"{% endif %}>
                                &nbsp;{{ value.value }}
                            </label>
                        {% endfor %}
                        <label for="value_for_{{ element.code }}_00" class="radio{% if not attribute_values | length %} checked{% endif %}">
                            <input id="value_for_{{ element.code }}_00" type="radio" value="0" name="main_value" {% if not attribute_values | length %}checked="checked"{% endif %}>
                            &nbsp;N/A
                        </label>
                    {% else %}
                        {% for value in element.availableMainValues %}
                            {% set checked = (value in attribute_values) and (value.mainValue is not null) %}
                            <label for="value_for_{{ element.code }}_{{ value.id }}" class="checkbox{% if checked %} checked{% endif %}">
                                <input id="value_for_{{ element.code }}_{{ value.id }}" type="checkbox" name="main_value[]" value="{{ value.id }}" {% if (value in attribute_values) and (value.mainValue is not null) %}checked="checked"{% endif %}>
                                &nbsp;{{ value.value }}
                            </label><br>
                        {% endfor %}
                    {% endif %}
                {% endif %}
                <span class="">{{ element.name }}</span> :<br>
            {% endif %}
                {% if element.typeUnique %}
                    {% set v = plant.getAttributeUniqueValueByCode(element.code) %}
                    <textarea name="main_value" class="w-full bg-transparent">{% if v %}{{ v.value }}{% endif %}</textarea>
                {% else %}
                    {% set attribute_values = plant.attributeValuesByCode(element.code) %}
                    {% if not element.typeMultiple %}
                        {% if (element.mainValue is null) %}
                            {% set values = element.availableValues %}
                        {% else %}
                            {% set values = element.availableNonMainValues %}
                        {% endif %}
                        {% if not values | length %}no value{% endif %}
                        {% for value in values %}
                            {% set checked = (value in attribute_values) and ((element.mainValue is null) or (value.mainValue is null)) %}
                            <label for="value_for_{{ element.code }}_{{ value.id }}" class="radio{% if checked %} checked{% endif %}">
                                <input id="value_for_{{ element.code }}_{{ value.id }}" type="radio" name="value" value="{{ value.id }}" {% if checked %}checked="checked"{% endif %}>
                                &nbsp;{{ value.value }}
                            </label><br>
                        {% endfor %}
                        <label for="value_for_{{ element.code }}_00" class="radio{% if not attribute_values | length %} checked{% endif %}">
                            <input id="value_for_{{ element.code }}_00" type="radio" value="0" name="value" {% if not attribute_values | length %}checked="checked"{% endif %}>
                            &nbsp;N/A
                        </label>
                    {% else %}
                        {% if (element.mainValue is null) %}
                            {% set values = element.availableValues %}
                        {% else %}
                            {% set values = element.availableNonMainValues %}
                        {% endif %}
                        {% if not values | length %}no value{% endif %}
                        {% for value in values %}
                            {% set checked = (value in attribute_values) and ((element.mainValue is null) or (value.mainValue is null)) %}
                            <label for="value_for_{{ element.code }}_{{ value.id }}" class="checkbox{% if checked %} checked{% endif %}">
                                <input id="value_for_{{ element.code }}_{{ value.id }}" type="checkbox" name="value[]" value="{{ value.id }}" {% if (value in attribute_values) and (value.mainValue is not null) %}checked="checked"{% endif %}>
                                &nbsp;{{ value.value }}
                            </label><br>
                        {% endfor %}
                    {% endif %}
                {% endif %}
            </div>
        {% endif %}
    </form>
</div>

templates/attribute/_partial/default_line.html.twig
{% if (plant.attributeValuesByCode(element.code) | length) %}
    <div data-code="{{ element.code }}" data-type="attribute" data-id="{{ element.id }}" class="show">
        {% if element.typeNone %}
            <span class="">
                <a href="{{ path('plant_index',{ (element.code) : '1'}) }}">{{ element.name }}</a>
            </span>
        {% else %}
            {% if element.mainValue is not null %}
                <span class="">{{ element.mainValue.label }}</span> :
                {% if plant.mainAttributeValuesByCode(element.code) | length %}
                    {% for attribute_value in plant.mainAttributeValuesByCode(element.code) %}
                        {% if attribute_value.mainValue is not null %}
                            <div class="attribute-value bg-gray-200">
                                {% if element.typeUnique %}
                                    {{ attribute_value.value }}
                                {% else %}
                                    {% if attribute_value.value is not null %}<a class="hover:underline capitalize" href="{{ path('plant_index',{ (element.code) : attribute_value.id}) }}">{{ attribute_value.value }}</a>{% endif %}
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <i class="mdi mdi-code-brackets"></i>
                {% endif %}
                <br>
            {% endif %}
            <span class="">{{ element.name }}</span> :
            {% if plant.attributeValuesByCode(element.code) | length %}
                {% for attribute_value in plant.attributeValuesByCode(element.code) %}
                    {% if attribute_value.mainValue is null %}
                        <div class="attribute-value bg-gray-100">
                            {% if element.typeUnique %}
                                <span class="">{{ attribute_value.value }}</span>
                            {% else %}
                                {% if attribute_value.value is not null %}<a class="hover:underline capitalize" href="{{ path('plant_index',{ (element.code) : attribute_value.id}) }}">{{ attribute_value.value }}</a>{% endif %}
                            {% endif %}
                        </div>
                    {% endif %}
                {% endfor %}
            {% else %}
                <i class="mdi mdi-code-brackets"></i>
            {% endif %}
        {% endif %}
    </div>
{% endif %}

templates/attribute/_partial/default_tiny.html.twig
{% if (plant.attributeValuesByCode(element.code) | length) %}
    <div data-code="{{ element.code }}" data-type="attribute" data-id="{{ element.id }}" class="show">
        {% if element.typeNone %}
            <span class=""><a class="hover:underline capitalize" href="{{ path('plant_index',{ (element.code) : '1'}) }}">{{ element.name }}</a></span>
        {% else %}
            {% if element.mainValue is not null %}
                {% for attribute_value in plant.mainAttributeValuesByCode(element.code) %}
                    {% if attribute_value.mainValue is not null %}
                        {% if element.typeUnique %}
                            {{ attribute_value.value }}
                        {% else %}
                            {% if attribute_value.value is not null %}<a class="hover:underline capitalize" href="{{ path('plant_index',{ (element.code) : attribute_value.id}) }}">{{ attribute_value.value }}</a>{% endif %}
                        {% endif %}
                    {% endif %}
                {% endfor %}
                <br>
            {% endif %}
            {% for attribute_value in plant.attributeValuesByCode(element.code) %}
                {% if attribute_value.mainValue is null %}
                    {% if element.typeUnique %}
                        {{ attribute_value.value }}
                    {% else %}
                        {% if attribute_value.value is not null %}<a class="hover:underline capitalize" href="{{ path('plant_index',{ (element.code) : attribute_value.id}) }}">{{ attribute_value.value }}</a>{% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}
        {% endif %}
    </div>
{% endif %}

templates/attribute/_partial/drought_tolerance_block.html.twig
{% if (plant.attributeValuesByCode(element.code) | length) %}
    {% set attribute_value = plant.attributeValuesByCode(element.code).first.value %}
    <div data-code="{{ element.code }}" data-type="attribute" data-id="{{ element.id }}" class="show">
        <span class="uppercase">{{ element.name }}</span>
{#        <a href="{{ path('plant_index',{ (element.code) : element.id}) }}">#}
            <div class="grid grid-cols-5">
                {% for i in 1..5 %}
                    {% if i > attribute_value %}
                        <div class="bg-contain bg-no-repeat bg-center bg-img h-12 w-12" style="--bg-image: url({{ asset('build/img/picto/goutte_vide.png') }})"></div>
                    {% else %}
                        <div class="bg-contain bg-no-repeat bg-center bg-img h-12 w-12" style="--bg-image: url({{ asset('build/img/picto/goutte_pleine.png') }})"></div>
                    {% endif %}
                {% endfor %}
            </div>
{#        </a>#}
    </div>
{% endif %}

templates/attribute/_partial/family_edit.html.twig
<form action="{{ path('plant_edit_family',{'id':plant.id}) }}" onsubmit="return false;" class="seamless">
    <input type="hidden" name="_csrf_token" value="{{ csrf_token('plant_edit_family') }}" >
    Famille :
    <label for="family" class="cursor-pointer">{% if not plant.Family %}-- Aucune --{% else %}{{ plant.Family.Name }}{% endif %}</label>
    <select name="value" id="family" class="hidden">
        <option value="-1" {% if not plant.family %}selected="selected"{% endif %}>-- Aucune --</option>
        <option value="0">-- (+) Ajouter --</option>
        {% for family in families %}
            <option value="{{ family.id }}" {% if plant.family and plant.family.id == family.id %}selected="selected"{% endif %}>{{ family.name }}</option>
        {% endfor %}
    </select>
    <div class="flex flex-wrap justify-center">
        <input type="text" id="family_name" name="name" value="" class="hidden border border-black">
        <button id="family_name_submit" class="hidden bg-gray-900 text-white">Ok</button>
    </div>
</form>

templates/attribute/_partial/filter.html.twig
<h4>{{ attribute.name }}</h4>
<div class="content">
    {% if attribute.isTypeNone %}
        <label class="inline-flex items-center mt-3 cursor-pointer" for="a_{{ attribute.code }}">
            <input id="a_{{ attribute.code }}" name="{{ attribute.code }}" type="checkbox" class="form-checkbox h-5 w-5 text-blue-600" data-f-value="1" value="1" {% if attributes_values[attribute.code] is defined %} checked="checked" {% endif %}>
            <span class="ml-2 text-gray-700">oui ?</span>
        </label>
    {% else %}
        <ul class="unstyled">
            {% for value in attribute.availableValues %}
                <li>
                    <label class="inline-flex items-center mt-3 cursor-pointer" for="filter_{{ attribute.code }}_{{ value.id }}">
                        <input id="filter_{{ attribute.code }}_{{ value.id }}" name="{{ attribute.code }}[]" type="checkbox" class="form-checkbox h-5 w-5 text-blue-600" value="{{ value.id }}" data-f-value="{{ value.id }}" {% if attributes_values[attribute.code] is defined and value in attributes_values[attribute.code] %} checked="checked" {% endif %}>
                        <span class="ml-2 text-gray-700">{{ value.value | raw }}</span>
                    </label>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
</div>

templates/attribute/_partial/foliage_block.html.twig
<span class="attrtitle">Feuillage</span>
{% if (plant.attributeValuesByCode(element.code) | length) or (edit) %}
    <div class="bg-contain bg-no-repeat bg-top pt-8 text-green-700 show bg-img h-30 w-30 text-center m-auto" data-code="{{ element.code }}" data-type="attribute" data-id="{{ element.id }}" style="--bg-image: url({{ asset('build/img/picto/foliage_'~plant.getAttributeValuesByCode('foliage').first.code~'.png') }})">
        {% for attribute_value in plant.attributeValuesByCode(element.code) %}
            <a class="hover:underline uppercase text-xl" href="{{ path('plant_index',{ (element.code) : attribute_value.id}) }}">
                {{ attribute_value.value }}
            </a>
        {% endfor %}
        <br>
        {{ plant.getAttributeValuesByCode('leaf_density').first.value }}
    </div>
{% endif %}

templates/attribute/_partial/foliage_line.html.twig
{% if (plant.attributeValuesByCode(element.code) | length) or (edit) %}
    <div class="bg-contain bg-no-repeat show bg-img text-green-800 " data-code="{{ element.code }}" data-type="attribute" data-id="{{ element.id }}" style="--bg-image: url({{ asset('build/img/picto/foliage_'~plant.getAttributeValuesByCode('foliage').first.code~'.png') }})">
            {% for attribute_value in plant.attributeValuesByCode(element.code) %}
                <a class="hover:underline uppercase text-xl" href="{{ path('plant_index',{ (element.code) : attribute_value.id}) }}">
                    {{ attribute_value.value }}
                </a>
            {% endfor %}
        <br>
        {{ plant.getAttributeValuesByCode('leaf_density').first.value }}
    </div>
{% endif %}

templates/attribute/_partial/insolation_block.html.twig
<span class="attrtitle">Exposition</span>
{% if (plant.attributeValuesByCode(element.code) | length) %}
    {% if plant.getMainAttributeValuesByCode('insolation').first %}
        {% set insolation = plant.getMainAttributeValuesByCode('insolation').first.code %}
    {% else %}
        {% set insolation = plant.getAttributeValuesByCode('insolation').first.code %}
    {% endif %}
    <div class="bg-contain bg-center bg-no-repeat py-6 text-yellow-900 show bg-img h-25 w-25 text-center m-auto" data-code="insolation" data-type="attribute" data-id="{{ element.id }}" style="--bg-image: url({{ asset('build/img/picto/insolation_'~insolation~'.png') }})">
            {% for attribute_value in plant.mainAttributeValuesByCode('insolation') %}
                {% if attribute_value.mainValue is not null %}
                    {% if element.typeUnique %}
                        {{ attribute_value.value }}
                    {% else %}
                        {% if attribute_value.value is not null %}
                            <a class="hover:underline text-xl font-black uppercase" href="{{ path('plant_index',{ 'insolation' : attribute_value.id}) }}">
                            {{ attribute_value.value }}</a>{% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}
                <br>
            {% for attribute_value in plant.attributeValuesByCode('insolation') %}
                {% if attribute_value.mainValue is null %}
                    {% if element.typeUnique %}
                        <span class="uppercase">{{ attribute_value.value }}</span>
                    {% else %}
                        {% if attribute_value.value is not null %}
                            <a class="hover:underline uppercase" href="{{ path('plant_index',{ 'insolation' : attribute_value.id}) }}">
                            {{ attribute_value.value }}</a>{% endif %}
                    {% endif %}
                {% endif %}
            {% endfor %}
    </div>
{% endif %}

templates/attribute/_partial/line_edit.html.twig
<li data-code="{{ attribute.code }}" data-type="attribute" data-id="{{ attribute.id }}">
    <form action="{{ path('plant_attribute_edit',{'id':plant.id,'attribute':attribute.id}) }}" onsubmit="return attributeLineEditSubmit(this)">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('plant_attribute_edit_'~attribute.code) }}" >
    {% if attribute.typeNone %}
        <label for="value"><input type="checkbox" {% if plant.attributeValuesByCode(attribute.code) | length %}checked="checked"{% endif %} name="value" value="{{ attribute.code }}">&nbsp;{{ attribute.name }}</label>
    {% else %}
        {% if attribute.mainValue is not null %}
            <b>{{ attribute.mainValue.label }}</b> :
            {% if attribute.typeUnique %}
                {% set attribute_value = plant.mainAttributeValuesByCode(attribute.code).first %}
                <input type="text" value="{% if attribute_value %}{{ attribute_value.value }}{% endif %}" name="main_value">
            {% else %}
                {% set attribute_values = plant.mainAttributeValuesByCode(attribute.code) %}
                <select name="main_value{% if attribute.typeMultiple %}[]{% endif %}" {% if attribute.typeMultiple %}multiple{% endif %}>
                    {% for value in attribute.availableMainValues %}
                        <option value="{{ value.id }}" {% if (value in attribute_values) and (value.mainValue is not null) %}selected="selected"{% endif %}>{{ value.value }}</option>
                    {% endfor %}
                    {% if not attribute.typeMultiple %}
                        <option value="0" {% if not attribute_values | length %}selected="selected"{% endif %}></option>
                    {% endif %}
                </select>
            {% endif %}
            <br>
        {% endif %}
        <b>{{ attribute.name }}</b> :
        {% if attribute.typeUnique %}
            {% set attribute_value = plant.attributeValuesByCode(attribute.code).first %}
            <input type="text" value="{% if attribute_value %}{{ attribute_value.value }}{% endif %}" name="value">
        {% else %}
            {% set attribute_values = plant.attributeValuesByCode(attribute.code) %}
            <select name="value{% if attribute.typeMultiple %}[]{% endif %}" {% if attribute.typeMultiple %}multiple{% endif %}>
                {% if (attribute.mainValue is null) %}
                    {% set values = attribute.availableValues %}
                {% else %}
                    {% set values = attribute.availableNonMainValues %}
                {% endif %}
                {% for value in values %}
                    <option value="{{ value.id }}" {% if (value in attribute_values) and ((attribute.mainValue is null) or (value.mainValue is null)) %}selected="selected"{% endif %}>{{ value.value }}</option>
                {% endfor %}
                {% if not attribute.typeMultiple %}
                <option value="0" {% if not attribute_values | length %}selected="selected"{% endif %}></option>
                {% endif %}
            </select>
        {% endif %}

    {% endif %}
        <input type="submit" value="Ok">
    </form>
</li>

templates/attribute/_partial/watering_needs_block.html.twig
{% if (plant.attributeValuesByCode(element.code) | length) %}
    {% set attribute_value = plant.attributeValuesByCode(element.code).first.value %}
    <div data-code="{{ element.code }}" data-type="attribute" data-id="{{ element.id }}" class="show">
        <span class="attrtitle">{{ element.name }}</span>
{#        <a href="{{ path('plant_index',{ (element.code) : element.id}) }}">#}
            <div class="grid grid-cols-5">
                {% for i in 1..5 %}
                    {% if i > attribute_value %}
                        <div class="bg-contain bg-no-repeat bg-center bg-img h-12 w-12" style="--bg-image: url({{ asset('build/img/picto/goutte_vide.png') }})"></div>
                    {% else %}
                        <div class="bg-contain bg-no-repeat bg-center bg-img h-12 w-12" style="--bg-image: url({{ asset('build/img/picto/goutte_pleine.png') }})"></div>
                    {% endif %}
                {% endfor %}
            </div>
{#        </a>#}
    </div>
{% endif %}